version: '2'
services:
  node:
    build: .
    command: node_modules/.bin/grunt
    volumes:
      - .:/var/www
      - /var/www/node_modules
    environment:
      NODE_ENV: development
    ports:
      - "80:3000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

